### ISSUE TITLE
Need own modules code

### ISSUE THREAD

**Issue by saikiranvanam** [SabareeshIyer/Brain-tumor-detection-in-3D-MRIs-using-DCGAN#2]
I'm facing error " ModuleNotFoundError: No module named 'medpy'" for "from medpy.io import load"
Can you provide me code for that module?

**Comment by smallrookie** [comment]
you can try:
`sudo apt-get install libboost-python-dev build-essential`
`sudo pip install medpy`
http://loli.github.io/medpy/index.html
